apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-v2
  namespace: default
  labels:
    app: echoserver
    version: v2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: echoserver
      version: v2
  template:
    metadata:
      labels:
        app: echoserver
        version: v2
    spec:
      containers:
        - name: echoserver
          image: zotovkem86/proxy-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
