apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: echoserver-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver
  namespace: default
spec:
  host: echoserver-service
  subsets:
    - name: v1
      labels:
        version: "v1"
    - name: v2
      labels:
        version: "v2"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-virtual-service
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - default/echoserver-gateway
  http:
    - route:
        - destination:
            host: echoserver-service
            port:
              number: 80
            subset: v1
          weight: 50
        - destination:
            host: echoserver-service
            port:
              number: 80
            subset: v2
          weight: 50
